set(HELLO_QML_SOURCE
  ${CMAKE_SOURCE_DIR}/src/hello-qml/main.cpp
)
set(HELLO_QML_QML
  src/hello-qml/qml/Main.qml
)
set(SIGNAL_SLOT_SOURCE
  ${CMAKE_SOURCE_DIR}/src/signal-slot/firefox.cpp
  ${CMAKE_SOURCE_DIR}/src/signal-slot/internet_explorer.cpp
  ${CMAKE_SOURCE_DIR}/src/signal-slot/main.cpp
  ${CMAKE_SOURCE_DIR}/src/signal-slot/user_interactor.cpp
)
set(SIGNAL_SLOT_QML
)
set(QOBJECT_TREE_SOURCE
  ${CMAKE_SOURCE_DIR}/src/qobject-tree/application_window.cpp
  ${CMAKE_SOURCE_DIR}/src/qobject-tree/main.cpp
)
set(QOBJECT_TREE_QML
)
set(INTRO_QUICK_SOURCE
  ${CMAKE_SOURCE_DIR}/src/intro-quick/main.cpp
)
set(INTRO_QUICK_QML
  src/intro-quick/qml/Main.qml
  src/intro-quick/qml/Main2.qml
)
set(POS_LAYOUT_SOURCE
  ${CMAKE_SOURCE_DIR}/src/pos-layout/main.cpp
)
set(POS_LAYOUT_QML
  src/pos-layout/qml/Main.qml
)
set(CUSTOM_QML_SOURCE
  ${CMAKE_SOURCE_DIR}/src/custom-qml/main.cpp
)
set(CUSTOM_QML_QML
  src/custom-qml/qml/AudioInfoBox.qml
  src/custom-qml/qml/Main.qml
  src/custom-qml/qml/TextBotton.qml
)
set(SONG_PLAYER_SOURCE
  ${CMAKE_SOURCE_DIR}/src/song-player/main.cpp
)
set(SONG_PLAYER_QML
  src/song-player/qml/AudioInfoBox.qml
  src/song-player/qml/ImageBotton.qml
  src/song-player/qml/Main.qml
)
set(SONG_PLAYER_RESOURCE
  src/song-player/asset/icon/app_icon.ico
  src/song-player/asset/icon/next_icon.png
  src/song-player/asset/icon/pause_icon.png
  src/song-player/asset/icon/play_icon.png
  src/song-player/asset/icon/previous_icon.png
  src/song-player/asset/image/song_1.jpg
  src/song-player/asset/image/song_2.jpg
  src/song-player/asset/image/song_3.jpg
  src/song-player/asset/video/video_1.avi
)
