set(HELLO_QML_SOURCE
  ${CMAKE_SOURCE_DIR}/src/hello-qml/main.cpp
)
set(HELLO_QML_QML
  src/hello-qml/qml/Main.qml
)
set(SIGNAL_SLOT_SOURCE
  ${CMAKE_SOURCE_DIR}/src/signal-slot/firefox.cpp
  ${CMAKE_SOURCE_DIR}/src/signal-slot/internet_explorer.cpp
  ${CMAKE_SOURCE_DIR}/src/signal-slot/main.cpp
  ${CMAKE_SOURCE_DIR}/src/signal-slot/user_interactor.cpp
)
set(SIGNAL_SLOT_QML
)
set(QOBJECT_TREE_SOURCE
  ${CMAKE_SOURCE_DIR}/src/qobject-tree/application_window.cpp
  ${CMAKE_SOURCE_DIR}/src/qobject-tree/main.cpp
)
set(QOBJECT_TREE_QML
)
set(INTRO_QUICK_SOURCE
  ${CMAKE_SOURCE_DIR}/src/intro-quick/main.cpp
)
set(INTRO_QUICK_QML
  src/intro-quick/qml/Main.qml
  src/intro-quick/qml/Main2.qml
)
set(POS_LAYOUT_SOURCE
  ${CMAKE_SOURCE_DIR}/src/pos-layout/main.cpp
)
set(POS_LAYOUT_QML
  src/pos-layout/qml/Main.qml
)
set(CUSTOM_QML_SOURCE
  ${CMAKE_SOURCE_DIR}/src/custom-qml/main.cpp
)
set(CUSTOM_QML_QML
  src/custom-qml/qml/AudioInfoBox.qml
  src/custom-qml/qml/Main.qml
  src/custom-qml/qml/TextBotton.qml
)
set(SONG_PLAYER_SOURCE
  ${CMAKE_SOURCE_DIR}/src/song-player/main.cpp
  ${CMAKE_SOURCE_DIR}/src/song-player/player_controller.cpp
)
set(SONG_PLAYER_QML_CPP_SOURCE
  ${CMAKE_SOURCE_DIR}/src/song-player/audio_info.cpp
  ${CMAKE_SOURCE_DIR}/src/song-player/audio_info.h
)
set(SONG_PLAYER_QML
  src/song-player/qml/AudioInfoBox.qml
  src/song-player/qml/ImageBotton.qml
  src/song-player/qml/Main.qml
)
set(SONG_PLAYER_RESOURCE
  src/song-player/asset/audio/air_on_the_g_string.mp3
  src/song-player/asset/audio/eine_kleine_nachtmusik.mp3
  src/song-player/asset/audio/symphony_no_5.mp3
  src/song-player/asset/icon/app_icon.ico
  src/song-player/asset/icon/next_icon.png
  src/song-player/asset/icon/pause_icon.png
  src/song-player/asset/icon/play_icon.png
  src/song-player/asset/icon/previous_icon.png
  src/song-player/asset/image/song_1.jpg
  src/song-player/asset/image/song_2.jpg
  src/song-player/asset/image/song_3.jpg
  src/song-player/asset/video/video_1.avi
)
set(SONG_PLAYER_WITH_HTTP_SOURCE
  ${CMAKE_SOURCE_DIR}/src/song-player-with-http/AudioInfo.cpp
  ${CMAKE_SOURCE_DIR}/src/song-player-with-http/AudioInfoModel.cpp
  ${CMAKE_SOURCE_DIR}/src/song-player-with-http/AudioSearchModel.cpp
  ${CMAKE_SOURCE_DIR}/src/song-player-with-http/main.cpp
  ${CMAKE_SOURCE_DIR}/src/song-player-with-http/PlayerController.cpp
)
set(SONG_PLAYER_WITH_HTTP_QML_CPP_SOURCE
  ${CMAKE_SOURCE_DIR}/src/song-player-with-http/AudioInfo.cpp
  ${CMAKE_SOURCE_DIR}/src/song-player-with-http/AudioInfo.h
  ${CMAKE_SOURCE_DIR}/src/song-player-with-http/AudioSearchModel.cpp
  ${CMAKE_SOURCE_DIR}/src/song-player-with-http/AudioSearchModel.h
)
set(SONG_PLAYER_WITH_HTTP_QML
  src/song-player-with-http/qml/AudioInfoBox.qml
  src/song-player-with-http/qml/ImageButton.qml
  src/song-player-with-http/qml/main.qml
  src/song-player-with-http/qml/PlaylistPanel.qml
  src/song-player-with-http/qml/SearchField.qml
  src/song-player-with-http/qml/SearchPanel.qml
)
set(SONG_PLAYER_WITH_HTTP_RESOURCE
  src/song-player-with-http/assets/audio/air_on_the_g_string.mp3
  src/song-player-with-http/assets/audio/eine_kleine_nachtmusik.mp3
  src/song-player-with-http/assets/audio/reprezentuje_biede.mp3
  src/song-player-with-http/assets/audio/symphony_no_5.mp3
  src/song-player-with-http/assets/icons/add_icon.png
  src/song-player-with-http/assets/icons/app_icon.ico
  src/song-player-with-http/assets/icons/close_icon.png
  src/song-player-with-http/assets/icons/menu_icon.png
  src/song-player-with-http/assets/icons/next_icon.png
  src/song-player-with-http/assets/icons/pause_icon.png
  src/song-player-with-http/assets/icons/play_icon.png
  src/song-player-with-http/assets/icons/previous_icon.png
  src/song-player-with-http/assets/icons/search_icon.png
  src/song-player-with-http/assets/icons/trash_icon.png
  src/song-player-with-http/assets/images/song_1.jpg
  src/song-player-with-http/assets/images/song_2.jpg
  src/song-player-with-http/assets/images/song_3.jpg
  src/song-player-with-http/assets/videos/video_1.avi
)
